### ISSUE TITLE
Problems with file names after upgrading to 4.8.0 (unicode)

### ISSUE THREAD

**Issue by crash-bash** [JrCs/docker-crashplan#25] opened 2016-11-09 09:20 UTC
Hello!

After upgrading to 4.8.0 I have a problem with the localized names of files and folders (screenshot attached). Long ago, this problem was already. There was something with Java configuration (unicode).

![123](https://cloud.githubusercontent.com/assets/23354873/20132978/9714f022-a676-11e6-8a06-7b581193c40d.PNG)

P.S. Useful links (maybe): 1) https://lesressourcesduweb.wordpress.com/2015/05/01/how-to-solve-the-crashplan-utf8-problem-on-freenas/ 2) https://bbs.archlinux.org/viewtopic.php?id=144557

**Comment by ChristianLindkvist** [comment] 2016-11-20 11:25
Hi, 
I just tried to use Docker and Crashplan and this problem arose, I lost 14 GB of files because the foldernames where unrecognizable. I tried the different solutions that you link to, I couldnt get it to work though, seemed like editing CrashPlanEngine and removing the parts that were mentioned in article 2 that you link to didnt stick. When I restarted the container it still had the section in the file. 

Did you get this to work somehow because I had to go back to the more conventional (prone to halting on updates) Crashplan-app?

Christian

**Comment by JrCs** [comment] 2016-11-20 13:35
Perhaps forcing LC_ALL to en_US.UTF-8 in docker run will do the job (add -e LC_ALL=en_US.UTF-8 to the docker run arguments)

**Comment by ChristianLindkvist** [comment] 2016-11-20 18:57
I am running the container in Docker on a Synology NAS and in the UI I have set the environment variables to sv_SE.UTF-8 (which was C.UTF-8 by default) and restarted but it doesnt seem to take. Isn´t that the same as what you are proposing?

I tried changing files such as run.conf because I somehow thought that I needed to change -Dfile.encoding=UTF-8 to something else but that file just reverted back to the original content when I restarted the container. 

Same thing with CrashPlanEngine in which there is a passage:

if [[ ${LC_ALL} ]]; then
        LOCALE=`sed 's/\..*//g' <<< ${LC_ALL}`
        export LC_ALL="${LOCALE}.UTF-8"
elif [[ ${LC_CTYPE} ]]; then
        LOCALE=`sed 's/\..*//g' <<< ${LC_CTYPE}`
        export LC_CTYPE="${LOCALE}.UTF-8"
elif [[ ${LANG} ]]; then
        LOCALE=`sed 's/\..*//g' <<< ${LANG}`
        export LANG="${LOCALE}.UTF-8"
else
        export LANG="en_US.UTF-8"
fi

And I tried changing it and even removing it but that didnt change the outcome, and when I removed it, it just came back after restart.

**Comment by kkopachev** [comment] 2016-11-21 10:55
Running this and restarting service inside container helped:
```
ALPINE_GLIBC_BASE_URL="https://github.com/sgerrand/alpine-pkg-glibc/releases/download" && \
    ALPINE_GLIBC_PACKAGE_VERSION="2.23-r3" && \
    ALPINE_GLIBC_BASE_PACKAGE_FILENAME="glibc-$ALPINE_GLIBC_PACKAGE_VERSION.apk" && \
    ALPINE_GLIBC_BIN_PACKAGE_FILENAME="glibc-bin-$ALPINE_GLIBC_PACKAGE_VERSION.apk" && \
    ALPINE_GLIBC_I18N_PACKAGE_FILENAME="glibc-i18n-$ALPINE_GLIBC_PACKAGE_VERSION.apk" && \
    apk add --no-cache --virtual=.build-dependencies wget ca-certificates && \
    wget \
        "https://raw.githubusercontent.com/andyshinn/alpine-pkg-glibc/master/sgerrand.rsa.pub" \
        -O "/etc/apk/keys/sgerrand.rsa.pub" && \
    wget \
        "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BASE_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_BIN_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_BASE_URL/$ALPINE_GLIBC_PACKAGE_VERSION/$ALPINE_GLIBC_I18N_PACKAGE_FILENAME" && \
    apk add --no-cache \
        "$ALPINE_GLIBC_BASE_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_BIN_PACKAGE_FILENAME" \
        "$ALPINE_GLIBC_I18N_PACKAGE_FILENAME" && \
    \
    rm "/etc/apk/keys/sgerrand.rsa.pub" && \
     /usr/glibc-compat/bin/localedef -i en_US -f UTF-8 en_US.UTF-8

 ./bin/CrashPlanEngine restart
```

**Comment by anderbytes** [comment] 2016-11-25 02:45
I CAN CONFIRM IT! WORKS!!!

I hope this gets fixed in the next images.... PLEASE!

**Comment by crash-bash** [comment] 2016-11-25 08:40
Thank you all for the detected workaround. I would be very grateful for the fixed image! Perhaps many people are simply not aware of this problem. All files with the localized names just quietly removed from the CrashPlan servers. Previously, my files on the CrashPlan servers volume occupied about 1.5 TB, and now 160 GB. All files with the localized names have been deleted in the background synchronization. It is invisible in everyday life. The problems begin when you want to restore data.

**Comment by anderbytes** [comment] 2016-11-25 16:44
@JrCs , if you haven't seen it yet... please implement the fix seen in post above from **kkopachev**.

That would be really helpful. Thanks!

**Comment by JrCs** [comment] 2016-11-25 17:12
Can you check the latest version ?

**Comment by anderbytes** [comment] 2016-11-25 17:14
My pleasure.... but I'll only be able to verify if the accented files are really included in the backup sent... by night when I get home and open the Crashplan Desktop.

**Comment by crash-bash** [comment] 2016-11-26 10:54
**@JrCs** Hooray!!! It works! Many thanks for a cool product! The new image works great for Synology.

**Closed as completed** 2016-11-26 11:45 UTC
