### ISSUE TITLE
CrashPlan Update 1435813200460 fails

### ISSUE THREAD

**Issue by Kyosfonica** [JrCs/docker-crashplan#3] opened 2016-03-11 14:00 UTC
The log files reports says:

Fri Mar 11 13:33:04 UTC 2016 : Sourcing ../../install.vars...
Fri Mar 11 13:33:04 UTC 2016 : Found INITDIR=/etc/init.d...
Fri Mar 11 13:33:04 UTC 2016 : Current CrashPlan Backup Engine:
root      6261     1  0 Mar03 ?        00:00:00 /opt/jre/bin/java -Dfile.encoding=UTF-8 -Dapp=CrashPlanService -DappBaseName=CrashPlan -Xms20m -Xmx3098m -Dsun.net.inetaddr.ttl=300 -Dnetworkaddress.cache.ttl=300 -Dsun.net.inetaddr.negative.ttl=0 -Dnetworkaddress.cache.negative.ttl=0 -Dc42.native.md5.enabled=false -classpath /usr/local/crashplan/lib/com.backup42.desktop.jar:/usr/local/crashplan/lang com.backup42.service.CPService
Fri Mar 11 13:33:04 UTC 2016 : Stopping using /etc/init.d/crashplan...
Stopping CrashPlan Engine ... OK
Fri Mar 11 13:33:14 UTC 2016 : Ensuring the UpgradeUI is not running.
Fri Mar 11 13:33:14 UTC 2016 : UpgradeUI is shut down.
Fri Mar 11 13:33:14 UTC 2016 : JAVACOMMON is set: /opt/jre/bin/java
Fri Mar 11 13:33:15 UTC 2016 : Current Java Version: 1.8
Fri Mar 11 13:33:15 UTC 2016: The Current java is not compatible. Embedding a compatible version.
Fri Mar 11 13:33:15 UTC 2016 : Download JVM from http://download.code42.com/installs/proserver/jre/jre-7-linux-x64.tgz
Fri Mar 11 13:33:15 UTC 2016 : downloading the JRE using /usr/bin/wget
Connecting to download.code42.com (216.17.8.19:80)
Connecting to download.code42.com (216.17.8.19:443)
wget: can't execute 'ssl_helper': No such file or directory
wget: error getting response: Connection reset by peer
Fri Mar 11 13:33:15 UTC 2016 : Unable to download JRE from http://download.code42.com/installs/proserver/jre/jre-7-linux-x64.tgz; please check network connection
Fri Mar 11 13:33:15 UTC 2016 : Starting using /etc/init.d/crashplan...
Starting CrashPlan Engine ... Using standard startup
OK

**Comment by elbandi** [comment] 2016-03-14 00:21
wget need to use with _--no-check-certificate_ parameter.

**Comment by JrCs** [comment] 2016-03-15 08:00
Never see this error: 'The Current java is not compatible'.
In what log do you see it ?
Which version of docker do you use ?
Do you use a docker-compose file ?

**Comment by Kyosfonica** [comment] 2016-03-15 08:22
I read those lines in the CrashPlan upgrade logs.
I didn't use any docker-compose file, just took the image and run the docker run command with the variables.
My docker version is: Docker version 1.6.2, build a263667
Running inside a synology OS, so is the Synology compilated Docker, i'm quite sure this is part of the cause.

**Comment by ning42** [comment] 2016-03-15 09:50
I see same error mesage from crashplan on my qnap

**Comment by JrCs** [comment] 2016-03-15 13:15
Docker version 1.6.2 is old.
Try using a more recent version.
Also get the latest image of this container.

**Comment by ning42** [comment] 2016-03-16 06:48
after the add of SSL and wget, the problem is solved on my qnap

**Comment by Kyosfonica** [comment] 2016-03-16 07:54
In your qnap or inside the docker container? If the second... how did you manage to enter the command line?

**Comment by Kyosfonica** [comment] 2016-03-16 08:04
I updated the docker container to the latest version that was released yesterday.
The update passed and now It is running the latest version again.

**Comment by Kyosfonica** [comment] 2016-03-16 08:19
@JrCs at least on Synology the oficial docker package is version 1.6.2 and there are no updates for the package. 
I know it is old and that I do not have a lot of cool features but if there is no complex docker container link in the background it works like a charm.

**Comment by JrCs** [comment] 2016-03-16 08:45
So it's seem to be an issue with old version of docker.
But with the add of openssl it's works now.
I close the issue. Feel free to comment if you have other issues.

**Closed as completed by JrCs** 2016-03-16 08:45 UTC
Labels: bug
